apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ticket-reservation-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SalifAbdoulSow18/ticket-reservation-app.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: ticket-reservation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true